const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

const SET_INITIAL_SEARCH_VALUE = 'SET_INITIAL_SEARCH_VALUE';

const GET_POKEMONS_LIST = 'GET_POKEMONS_LIST';

export { SET_SEARCH_VALUE, SET_INITIAL_SEARCH_VALUE, GET_POKEMONS_LIST };
